---
abstract: 'Compress and convert css, less, sass and javascript files'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-AssetPack
no_index:
  directory:
    - t
    - inc
requires:
  File::Which: 1.00
  IPC::Run3: 0.04
  Mojolicious: 4.30
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojolicious-Plugin-AssetPack
  homepage: https://metacpan.org/release/Mojolicious-Plugin-AssetPack
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/mojolicious-plugin-assetpack
version: 0.0102
