---
abstract: 'Compress and convert css, less, sass, javascript and coffeescript files'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-AssetPack
no_index:
  directory:
    - t
    - inc
requires:
  CSS::Minifier::XS: 0.01
  File::Which: 1.00
  IPC::Run3: 0.04
  JavaScript::Minifier::XS: 0.01
  Mojolicious: 5.00
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-assetpack/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-assetpack
  repository: https://github.com/jhthorsen/mojolicious-plugin-assetpack.git
version: 0.29
